### ISSUE TITLE
JDynmapGriefPrevention suport for GPP

### ISSUE THREAD

**Issue by evernife** [KaiKikuchi/Dynmap-GriefPreventionPlus#3]
#### Error Logs:
1. Console Error: [***haste.bin***](http://hastebin.com/cuyanuzuho.avrasm)

![image](https://cloud.githubusercontent.com/assets/11357801/18254855/a5b128fc-7378-11e6-8152-38632259aaf5.png)

#### New Suggestion
Make the [***JDynmap***](https://www.spigotmc.org/resources/jdynmapgriefprevention.818/) plugin work with GPP
Not that important ay all, but... it will be helpfull :D

**Comment by KaiKikuchi** [comment]
JDynmap's license is "All Rights Reserved"... the source code is not available. You may want to ask the plugin's developer to add GPP's support.

**Comment by KaiKikuchi** [comment]
The issue with Dynmap is caused by a claim being on a non-existant world, or a unloaded world.

**Comment by KaiKikuchi** [comment]
Hopefully fixed in v.0.9
